name: Build PDF from Markdown

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # erlaubt manuelles Starten Ã¼ber GitHub UI

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc and TinyTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          wget -qO- "https://yihui.org/gh/tinytex/install-bin-unix.sh" | sh
          export PATH=$PATH:/home/runner/.TinyTeX/bin/x86_64-linux
          tlmgr install xetex ulem geometry fancyhdr titlesec fontspec xcolor collection-fontsrecommended


      - name: Generate PDF from Markdown
        run: |
          mkdir -p output
          pandoc docs/*.md -o output/ABAP_Leitfaden.pdf --pdf-engine=xelatex --toc --metadata title="DSAG e.V. ABAP Leitfaden 2025"


      - name: Generate PDF from Markdown
        run: |
          export PATH=$PATH:/home/runner/.TinyTeX/bin/x86_64-linux
          mkdir -p output
          pandoc docs/*.md -o output/documentation.pdf \
          pandoc docs/*.md -o output/ABAP_Leitfaden.pdf --pdf-engine=xelatex --toc --metadata title="DSAG e.V. ABAP Leitfaden 2025"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ABAP_Leitfaden-pdf
          path: output/ABAP_Leitfaden.pdf
          
